### PR TITLE
Add example test files for both HL7 and FHIR for testing and as examples

### PR DESCRIPTION
**Pull request by BradySkylight**

### CODE REVIEW

**Comment by celestemespinoza** [comment]
Task linked: [CU-2vz8d62 Implement manual end-to-end testing of the ingestion pipeline](https://app.clickup.com/t/2vz8d62)

**Review by nickclyde — APPROVED** [review]
Nice, thanks for adding these!

**Comment by BradySkylight** [comment]
@nickclyde @DanPaseltiner - Are the files named appropriately?  Should I make any changes there?  Do they make sense?  Any formatting suggestions?

**Comment by nickclyde** [comment]
I think the naming and file locations makes sense as is!

**Pull request merged**
