### PR TITLE
Various Terraform fixes

### PR DESCRIPTION
**Pull request by nickclyde**
Needed to fix a bunch of things to get a successful deploy.

### CODE REVIEW

**Review by BradySkylight — APPROVED** [review]
Nice job!  LGTM

**Comment by nickclyde** [comment]
Still having issues with this... the `add_patient_hash` function is failing to start with this error:
```
Could not fetch secret "projects/577891603445/secrets/PATIENT_HASH_SALT/versions/projects/577891603445/secrets/PATIENT_HASH_SALT/versions/1" for environment variable "PATIENT_HASH_SALT". Instance startup will now abort: The provided Secret Version ID [projects/577891603445/secrets/PATIENT_HASH_SALT/versions/projects/577891603445/secrets/PATIENT_HASH_SALT/versions/1] does not match the expected format [projects/*/secrets/*/versions/*]
```

Still trying to sort out why the format of the version name is wrong...

**Comment by nickclyde** [comment]
Successful deploy:
https://github.com/CDCgov/phdi-google-cloud/runs/8163218886?check_suite_focus=true

**Review by BradySkylight — APPROVED** [review]
Excellent work!

**Pull request merged**
